- id: check-customapi-privilege
  name: Custom API Privilege Check
  description: Check for added customapi.xml has privilege configured correctly.
  entry: check-customapi-privilege
  language: python
  types: [file]
