- id: eslint
  name: ESLint for TypeScript
  description: Run ESLint on TypeScript files
  entry: powershell -ExecutionPolicy Bypass -File hooks/eslint.ps1
  language: system
  files: \.(ts|tsx)$
  require_serial: true
  types: [file]
  exclude: \.d\.ts$
