- id: eslint
  name: ESLint for TypeScript
  description: Run ESLint on TypeScript files
  entry: hooks/eslint
  language: script
  files: \.(ts|tsx)$
  require_serial: true
  types: [file, typescript]
  exclude: \.d\.ts$
