- id: check-added-large-files1
  name: Custom check for large files
  description: Check for added files larger than a specified size (custom version)
  entry: check-added-large-files1
  language: python
  types: [file]