-   id: check-added-large-files1
    name: check for added large files
    description: prevents giant files from being committed.
    entry: check-added-large-files1
    language: python

-   id: eslint
    name: ESLint for TypeScript and JavaScript
    description: Run ESLint on TypeScript and JavaScript files
    entry: pre-commit-hooks/eslint.ps1
    language: script
    files: \.(ts|tsx|js|jsx)$
    require_serial: true
    types: [file]
    exclude: \.d\.ts$
