- id: eslint
  name: ESLint for TypeScript
  description: Run ESLint on TypeScript files
  entry: bash hooks/eslint
  language: script
  files: \.(ts|tsx)$
  require_serial: true
  types: [file]
  exclude: \.d\.ts$
